security:
  oauth2:
    client:
      clientId: <client id>
      clientSecret: <client secret>
      accessTokenUri: https://login.microsoftonline.com/<tenant>/oauth2/token
      userAuthorizationUri: https://login.microsoftonline.com/<tenant>/oauth2/authorize
      clientAuthenticationScheme: form
      scope: openid
    resource:
      userInfoUri: https://graph.windows.net/me?api-version=1.6

logging:
  level:
    org.springframework.security: DEBUG
